// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwLdDswTaAUbloNj8IsBaHA0iWEXb8crE',
    appId: '1:360444353139:web:30ec130145ce8a6139e806',
    messagingSenderId: '360444353139',
    projectId: 'rejoice-greatly',
    authDomain: 'rejoice-greatly.firebaseapp.com',
    storageBucket: 'rejoice-greatly.firebasestorage.app',
    measurementId: 'G-80BQPXQZFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXI5Gb5l4omIlhNHOKXgPu1sfOsXQQ6Sg',
    appId: '1:360444353139:android:cbed5c03ba3ded1639e806',
    messagingSenderId: '360444353139',
    projectId: 'rejoice-greatly',
    storageBucket: 'rejoice-greatly.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYSv9eK1KXLisygEp63dvinZY7_3gGp1Y',
    appId: '1:360444353139:ios:921b81f7d96564ab39e806',
    messagingSenderId: '360444353139',
    projectId: 'rejoice-greatly',
    storageBucket: 'rejoice-greatly.firebasestorage.app',
    iosBundleId: 'com.example.churchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYSv9eK1KXLisygEp63dvinZY7_3gGp1Y',
    appId: '1:360444353139:ios:921b81f7d96564ab39e806',
    messagingSenderId: '360444353139',
    projectId: 'rejoice-greatly',
    storageBucket: 'rejoice-greatly.firebasestorage.app',
    iosBundleId: 'com.example.churchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwLdDswTaAUbloNj8IsBaHA0iWEXb8crE',
    appId: '1:360444353139:web:355e77045076c1e439e806',
    messagingSenderId: '360444353139',
    projectId: 'rejoice-greatly',
    authDomain: 'rejoice-greatly.firebaseapp.com',
    storageBucket: 'rejoice-greatly.firebasestorage.app',
    measurementId: 'G-DVZK78WSBW',
  );
}
