// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOLVdQ6zYGJQYgk5gfP2yvvLxZpMbFKyU',
    appId: '1:1053433403648:web:5cc2a686c91634bb96fbe5',
    messagingSenderId: '1053433403648',
    projectId: 'moodchangingcafe',
    authDomain: 'moodchangingcafe.firebaseapp.com',
    databaseURL: 'https://moodchangingcafe-default-rtdb.firebaseio.com',
    storageBucket: 'moodchangingcafe.firebasestorage.app',
    measurementId: 'G-5Q140V5N2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyrT00jKue3A31bW5g90Lz_Ffq1grIYYU',
    appId: '1:1053433403648:android:000cbe011b70be3796fbe5',
    messagingSenderId: '1053433403648',
    projectId: 'moodchangingcafe',
    databaseURL: 'https://moodchangingcafe-default-rtdb.firebaseio.com',
    storageBucket: 'moodchangingcafe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXRja7FQfgaar5IRsdbparRTs9xTJjECQ',
    appId: '1:1053433403648:ios:4281beec4c2e913c96fbe5',
    messagingSenderId: '1053433403648',
    projectId: 'moodchangingcafe',
    databaseURL: 'https://moodchangingcafe-default-rtdb.firebaseio.com',
    storageBucket: 'moodchangingcafe.firebasestorage.app',
    iosClientId: '1053433403648-id0o692vjp8v3kp3a4p9mdda1gsohjhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.churchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXRja7FQfgaar5IRsdbparRTs9xTJjECQ',
    appId: '1:1053433403648:ios:4281beec4c2e913c96fbe5',
    messagingSenderId: '1053433403648',
    projectId: 'moodchangingcafe',
    databaseURL: 'https://moodchangingcafe-default-rtdb.firebaseio.com',
    storageBucket: 'moodchangingcafe.firebasestorage.app',
    iosClientId: '1053433403648-id0o692vjp8v3kp3a4p9mdda1gsohjhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.churchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkunrPSq5j7UduXssVuCbK8WnYtNmsW3w',
    appId: '1:1053433403648:web:bfc5a70238696d4196fbe5',
    messagingSenderId: '1053433403648',
    projectId: 'moodchangingcafe',
    authDomain: 'moodchangingcafe.firebaseapp.com',
    databaseURL: 'https://moodchangingcafe-default-rtdb.firebaseio.com',
    storageBucket: 'moodchangingcafe.firebasestorage.app',
    measurementId: 'G-D54JJZJ5PM',
  );

}